sudo: required
services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)

before_install:
  - gem install bundler
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - cd tests
  - yarn install
  - yarn run test
  - cd ..
  # Deploy to docker-hub
  - bash ./deploy.dockerhub.sh

# Deploy to Docker Hub
# deploy:
#   provider: script
#   script: bash ./deploy.dockerhub.sh
#   on:
#     branch: master

# Deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: Scheduler
  env: Scheduler-env-2
  bucket_name: elasticbeanstalk-ap-south-1-729767835831
  bucket_path: Scheduler
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"